# openapi2-run.yaml
swagger: '2.0'
info:
  title: backend-api
  description: Deep Media Backend public APIs
  version: 1.0.0
schemes:
- https
produces:
- application/json
x-google-backend:
  address: https://deep-media-backend-evur3nagma-rj.a.run.app
paths:
    /health:
      get:
        summary: Health Check
        operationId: health
        responses:
          '200':
            description: A successful response
            schema:
              type: string