apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deep-media-backend
spec:
  template:
    spec:
      containers:
      - image: gcr.io/deepmedia-2021-06-11/deep-media-backend:latest

        env:
        # Scheduler to optimization jobs
        - name: PROJECT_ID
          value:
        - name: LOCATION_ID
          value:
        - name: TIMEZONE
          value:
        - name: OPTIMIZERS_TOPIC
          value:
        - name: OPTIMIZERS_CRON
          value:

        # Google Connector
        - name: GOOGLE_CLIENT_ID
          value:
        - name: GOOGLE_CLIENT_SECRET
          value:
        - name: GOOGLE_DEVELOPER_TOKEN
          value: